name: Build OpenCV xcframework

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Prepare Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

      - name: actions-setup-cmake
        uses: jwlawson/actions-setup-cmake@v1.13.1
        with:
          cmake-version: 3.28

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: opencv-spm

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Get version
        id: get_version
        working-directory: opencv-spm
        run: echo "VERSION=$(cat .version)" >> $GITHUB_OUTPUT

      - name: Checkout OpenCV
        uses: actions/checkout@v3
        with:
          repository: opencv/opencv
          ref: refs/tags/${{ steps.get_version.outputs.VERSION }}
          path: 'opencv'
      
      - name: Build xcframework
        working-directory: opencv
        env:
          IPHONEOS_DEPLOYMENT_TARGET: 12.0
          MACOSX_DEPLOYMENT_TARGET: 10.13
        run: |
          git apply $GITHUB_WORKSPACE/opencv-spm/opencv.patch
          pip3 install pathlib
          python3 platforms/apple/build_xcframework.py \
          --build_only_specified_archs \
          --macos_archs=x86_64,arm64 \
          --framework_name=OpenCV \
          --disable-bitcode -o build \
          --without highgui \
          --without video \
          --without videoio
          --without dnn \
          --without gapi \
          --without imgproc \
          --without highgui \
          --without java \
          --without js \
          --without ml \
          --without objdetect \
          --without photo \
          --without python \
          --without ts \
          --without video \
          --without videoio \
          --without world
        


      - name: Zip artifact
        working-directory: opencv
        run: zip -ry OpenCV.xcframework.zip build/OpenCV.xcframework

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: OpenCV.xcframework.zip
          path: opencv/OpenCV.xcframework.zip
          if-no-files-found: error
